### ISSUE TITLE
Thanks for your excellent work. I would like to ask when the code for the segmentation part of pointramba will be released?

### ISSUE THREAD

**Issue by JennyWow111** [xiaoyao3302/PoinTramba#4]
Thanks for your excellent work. I would like to ask when the code for the segmentation part of pointramba will be released?

**Comment by xiaoyao3302** [comment]
Hi, thanks for your interest in our work. We are improving our PoinTramba as the segmentation performance of our work is not very good. Currently, the segmentation part of our code is nearly the same as PointMamba, just replacing the backbone is OK. We hope to submit the improved method to CVPR and we will update the codes then.

**Comment by JennyWow111** [comment]
Thanks for your answer, I have another question. I see some code related to test in the code, but I don't see any command to use test. Is test needed for point cloud classification? If so, can you tell me the command to use test?

**Comment by xiaoyao3302** [comment]
You only need to focus on validate-related code, like Line 312 in the runner_finetune.py file. 
I used the test code to visualize the importance scores, which I made some modifications, as listed in the supplements. I will update the corresponding code later.

**Comment by JennyWow111** [comment]
OK, I got it, thank you very much
