### ISSUE TITLE
Classification visualization: test_tsne function cannot output TSNE graph

### ISSUE THREAD

**Issue by L1277471578** [xiaoyao3302/PoinTramba#7]
Hello, I want to use the **test_tsne** function in **runner_finetune. py** to test and output a tsne graph, but an error message appears:

File "/home/g512/liubin/PoinTramba/tools/runner_finetune.py", line 625, in test_tsne
test_only_tsne(base_model, test_dataloader, args, config, logger=logger)
File "/home/g512/liubin/PoinTramba/tools/runner_finetune.py", line 582, in test_only_tsne
_, concat_f = base_model(points)
ValueError: too many values to unpack (expected 2)

Later, I tried using the **test_tsne** function in **runner_test. py**, but the same error was reported. So, I performed a `points=points [: 2,:,:]` operation on **points**，this line went smoothly, but there were new errors：

File "/home/g512/liubin/PoinTramba/tools/runner_finetune.py", line 601, in test_only_tsne
test_feature = test_feature[index]
IndexError: The shape of the mask [2468] at index 0 does not match the shape of the indexed tensor [1560] at index 0

May I ask if a parameter needs to be set for dimensionality reduction?

**Comment by xiaoyao3302** [comment]
Oh, sorry for the misleading, the TSNE code is only tested during my experiments and may not be suitable for the current version. You can check the output of the model, and if I were correct, you should use the global feature as the input of tsne, which should be concat_f = base_model(points)[-1]. You can try this, and please update me with your up-to-date problem. We can fix it. Thanks.

**Comment by L1277471578** [comment]
After I changed **_, concat_f = base_model(points)** to **concat_f = base_model(points)[-1]**, an error occurred:
File "/home/g512/liubin/PoinTramba/tools/runner_finetune.py", line 601, in test_only_tsne
test_feature = test_feature[index]
IndexError: The shape of the mask [2468] at index 0 does not match the shape of the indexed tensor [1560] at index 0

**Comment by xiaoyao3302** [comment]
can you show me the shape of the test_feature?

**Comment by xiaoyao3302** [comment]
Besides, it's a typo, -1 should be -2.

**Comment by L1277471578** [comment]
![微信图片_20241202204626](https://github.com/user-attachments/assets/cf9b10b4-b5da-49ee-b9cc-4ae2ea719e18)

the shape of the test_feature is [1560]

**Comment by xiaoyao3302** [comment]
It is obviously not right, concat_f should be a feature. Could you please read the code more carefully and debug for some time to make sure you can understand what the code is doing? Solely asking on GitHub without reading the code is far from efficient.

**Comment by L1277471578** [comment]
Hello, I know _concat_f_ is a feature and have read and understood the code, but this issue has not been resolved yet. 
Now, there are 39 _concat_f_, each shape is [40]; and there are 39 _label_, of which 38 shapes are [64],  one is [36]. 
The shape of the _test_feature_ formed by concatenating is [1560] (40 * 39), while the corresponding _test_label_ is [2468] (38 * 64+36=2468). 
I think the problem lies here. I don't know why the shape of the _label_ and _concat_f_ are different, and only the shape of the last _label_ is [36], while the others are [64].  I hope you can give me some advice, thank you very much!!

This is the code for printing shapes and its output：
![微信图片_20241203211950](https://github.com/user-attachments/assets/08fee261-a266-4238-a576-de2ddcaa7849)
![微信图片_20241203211955](https://github.com/user-attachments/assets/ac1099ae-3b81-483b-b0c4-b5cb75b5544d)

**Comment by L1277471578** [comment]
I think the shape of _concat_f_ is correct because modelnet40 has 40 categories and the output shape is [40], which is reasonable. The question is why the _label_ are [64] and [36], and how should they be modified?

**Comment by xiaoyao3302** [comment]
Hi, I don't know how you set your dataloader, and [64] and [36] may be due to the drop_last parameter. Besides, please be aware of how the tsne works, and I don't think the shape of test_feature is 40 is correct. If you know how tsne works, it would be quite easy for you to fix the bug.

**Comment by L1277471578** [comment]
Thank you very much for your help. I have already resolved this issue and will
```
test_label = torch.cat(test_label, dim=0)
category_nums = config.model.cls_dim
index = test_label < category_nums
label_all = test_label[index]
test_feature = torch.cat(test_feature, dim=0)
test_feature = test_feature[index]
test_feature = test_feature.cpu().numpy()
label = label_all.cpu().numpy()
```
Changed to
```
test_label = torch.cat(test_label, dim=0)
test_feature = torch.cat(test_feature, dim=0)
test_feature = test_feature.cpu().numpy()
label = test_label.cpu().numpy()
```

But I compared the tsne plots of pointramba (with attention to SA) and pointmamba on Modelnet10, the same applies to modelnet40,  and the comparison is as follows (left: pointmamba, Right: pointramba）， Why is it that the feature differences of pointramba are not good?

 <img src="https://github.com/user-attachments/assets/76e238ef-c29d-4a8d-bb3a-aa392d1c18f3" width="400" />
<img src="https://github.com/user-attachments/assets/ba74bb32-81f0-45d2-adc7-61725ee7b1e6" width="400" />

**Comment by xiaoyao3302** [comment]
Hi, congratulations on the tsne. As for the visualizations, I wonder if you could check the performance of the model? If the performance is correct, i.e., PoinTramba is better than PointMamba, may I have you double-check the feature fed into the tsne? Please refer to line 1547 of the model.py, as we can see, the output feature is the feature after mapping, while the feature for classification is the feature without mapping, could you please modify the code, use the global_feature (line 1545) as the input of the tsne, and check the visualizations again? Thanks.

**Comment by xiaoyao3302** [comment]
The feature with mapping is used for calculating the importance scores, while the feature without mapping is used for classification, please mind the difference.

**Comment by L1277471578** [comment]
Thank you very much. I changed **concatenat_f=base_madel (points) [-2]** to **concatenat_f=base_madel (points) [-4]** and obtained a normal TSNE graph

 <img src="https://github.com/user-attachments/assets/636f06a8-9ae0-4b47-877f-f1b18a5fc398" width="400" />
